[build]
  command = "npm install && npm run build"
  publish = "build"
  functions = "functions"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  force = true
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200